#!/usr/bin/env python3
"""Compare D:\\app business modules with attendance_toolbox/python.

Normalizes CRLF/CR to LF, computes SHA256, classifies allowed adapter-only diffs
via *file-level canonical normalization* (not wide regexes), and writes
SOURCE_MANIFEST.json + _diff_report.txt under the toolbox python root.

Exit codes:
  0 — all equal, or only verified adapter-only differences
  1 — missing files or any non-adapter divergence
  2 — D:\\app (or APP_ROOT) unavailable (caller should skip local parity)

SOURCE_MANIFEST.json is fully generated by this script — do not hand-edit fields.
"""
from __future__ import annotations

import difflib
import hashlib
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

APP_ROOT = Path(os.environ.get("ATTENDANCE_APP_SOURCE_ROOT", r"D:/app"))
TOOLBOX_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = TOOLBOX_ROOT / "SOURCE_MANIFEST.json"
DIFF_REPORT_PATH = TOOLBOX_ROOT / "_diff_report.txt"

PAIRS = [
    "leave/calc_leave.py",
    "overtime/fill_overtime_fields.py",
    "overtime/rules_engine.py",
    "subsidy/calc_subsidy_deduction.py",
    "finally/calc_finally.py",
    "parttime/calc_parttime_summary.py",
    "dingtalk_sync.py",
]

# Only these two files may carry the verified HR adapter layer.
ADAPTER_ALLOWLIST = {
    "overtime/fill_overtime_fields.py",
    "finally/calc_finally.py",
}

# Exact two-line block injected so toolbox root is importable.
_BASE_PATH_BLOCK = (
    "if _BASE not in sys.path:\n"
    "    sys.path.insert(0, _BASE)\n"
)

# Import line: allow optional trailing comment / noqa only.
_IMPORT_COMPAT_RE = re.compile(
    r"^from excel_compat import load_workbook_compat(?:\s*#.*)?\n",
    re.MULTILINE,
)

# Pure call replacement: load_workbook_compat( → openpyxl.load_workbook(
# Reject if the same logical statement has trailing business expressions.
_COMPAT_CALL_RE = re.compile(r"\bload_workbook_compat\s*\(")
_TRAILING_BUSINESS_RE = re.compile(r"\)\s*;\s*\S")  # e.g. load_workbook_compat(path); score = 1


def normalize_bytes(raw: bytes) -> bytes:
    return raw.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load_normalized(path: Path) -> bytes:
    if not path.is_file():
        raise FileNotFoundError(str(path))
    return normalize_bytes(path.read_bytes())


def _has_impure_compat_call(text: str) -> bool:
    """True when a load_workbook_compat(...) line also carries extra business code."""
    for line in text.splitlines():
        if "load_workbook_compat" not in line:
            continue
        # Statement that continues with `; other_expr` after the call closes → impure.
        if _TRAILING_BUSINESS_RE.search(line):
            return True
        # Multiple statements on one line besides the compat call.
        if ";" in line:
            # Allow only pure `...load_workbook_compat(...);` nothing after.
            after_semi = line.split(";", 1)[1].strip()
            if after_semi:
                return True
    return False


def canonicalize_toolbox_adapter(rel: str, tbx_norm: bytes) -> tuple[bytes, bool]:
    """Strip verified adapter-only edits from allowlisted toolbox files.

    Returns (canonical_bytes, adapter_applied).
    If the file is not allowlisted, content is returned unchanged and
    adapter_applied is False.
    """
    if rel not in ADAPTER_ALLOWLIST:
        return tbx_norm, False

    text = tbx_norm.decode("utf-8", "replace")
    original = text

    if _has_impure_compat_call(text):
        # Do not strip; force business_divergence against app.
        return tbx_norm, False

    applied = False

    if _BASE_PATH_BLOCK in text:
        text = text.replace(_BASE_PATH_BLOCK, "", 1)
        applied = True

    new_text, n_import = _IMPORT_COMPAT_RE.subn("", text, count=1)
    if n_import:
        text = new_text
        applied = True

    # Replace pure load_workbook_compat( with openpyxl.load_workbook(
    if _COMPAT_CALL_RE.search(text):
        text = _COMPAT_CALL_RE.sub("openpyxl.load_workbook(", text)
        applied = True

    if text == original:
        return tbx_norm, False
    return text.encode("utf-8"), applied


def classify_difference(rel: str, app_raw: bytes, tbx_raw: bytes) -> str:
    """Return 'equal' | 'adapter_only' | 'business_divergence'.

    Inputs may still contain CRLF; LF normalization is applied first.
    """
    app_norm = normalize_bytes(app_raw)
    tbx_norm = normalize_bytes(tbx_raw)
    if app_norm == tbx_norm:
        return "equal"

    canonical, applied = canonicalize_toolbox_adapter(rel, tbx_norm)
    if applied and normalize_bytes(canonical) == app_norm:
        return "adapter_only"

    # After canonicalization still different, or non-allowlist diffs → business.
    return "business_divergence"


def build_manifest(app_root: Path, toolbox_root: Path) -> dict:
    entries = []
    unequal_business = 0
    adapter_only = 0
    equal_count = 0
    diff_sections: list[str] = []

    for rel in PAIRS:
        app_path = app_root / rel
        tbx_path = toolbox_root / rel
        entry = {
            "path": rel,
            "app_label": f"app/{rel}",
            "toolbox_relpath": rel.replace("\\", "/"),
            "app_exists": app_path.is_file(),
            "toolbox_exists": tbx_path.is_file(),
            "app_sha256": None,
            "toolbox_sha256": None,
            "equal": False,
            "difference_kind": None,
            "app_size": None,
            "toolbox_size": None,
            "error": None,
        }
        try:
            if not app_path.is_file():
                raise FileNotFoundError(f"app missing: {app_path}")
            if not tbx_path.is_file():
                raise FileNotFoundError(f"toolbox missing: {tbx_path}")
            app_norm = load_normalized(app_path)
            tbx_norm = load_normalized(tbx_path)
            entry["app_sha256"] = sha256_hex(app_norm)
            entry["toolbox_sha256"] = sha256_hex(tbx_norm)
            entry["app_size"] = len(app_norm)
            entry["toolbox_size"] = len(tbx_norm)
            kind = classify_difference(rel, app_norm, tbx_norm)
            entry["difference_kind"] = kind
            entry["equal"] = kind == "equal"
            if kind == "equal":
                equal_count += 1
            elif kind == "adapter_only":
                adapter_only += 1
                app_lines = app_norm.decode("utf-8", "replace").splitlines()
                tbx_lines = tbx_norm.decode("utf-8", "replace").splitlines()
                section = "\n".join(
                    difflib.unified_diff(
                        app_lines,
                        tbx_lines,
                        fromfile=f"app/{rel}",
                        tofile=f"toolbox/{rel}",
                        lineterm="",
                        n=2,
                    )
                )
                diff_sections.append(f"===== {rel} [adapter_only] =====\n{section}\n")
            else:
                unequal_business += 1
                app_lines = app_norm.decode("utf-8", "replace").splitlines()
                tbx_lines = tbx_norm.decode("utf-8", "replace").splitlines()
                section = "\n".join(
                    difflib.unified_diff(
                        app_lines,
                        tbx_lines,
                        fromfile=f"app/{rel}",
                        tofile=f"toolbox/{rel}",
                        lineterm="",
                        n=3,
                    )
                )
                diff_sections.append(f"===== {rel} [business_divergence] =====\n{section}\n")
        except Exception as exc:  # noqa: BLE001
            entry["error"] = str(exc)
            entry["difference_kind"] = "error"
            unequal_business += 1
            diff_sections.append(f"===== {rel} =====\nERROR: {exc}\n")
        entries.append(entry)

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "app_root_label": "app",
        "toolbox_root_relpath": "tools/attendance_toolbox/python",
        "normalization": "CRLF/CR -> LF; allowlist adapter strip for fill_overtime/finally",
        "pair_count": len(PAIRS),
        "equal_count": equal_count,
        "adapter_only_count": adapter_only,
        "business_divergence_count": unequal_business,
        "unequal_count": adapter_only + unequal_business,
        "files": entries,
        "_diff_sections": diff_sections,
        "_ok": unequal_business == 0,
    }


def write_outputs(manifest: dict) -> None:
    diff_sections = manifest.pop("_diff_sections", [])
    ok = manifest.pop("_ok", False)
    MANIFEST_PATH.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    report_body = (
        f"generated_at={manifest['generated_at']}\n"
        f"equal={manifest['equal_count']} adapter_only={manifest['adapter_only_count']} "
        f"business_divergence={manifest['business_divergence_count']} total={manifest['pair_count']}\n\n"
    )
    if diff_sections:
        report_body += "\n".join(diff_sections)
    else:
        report_body += "All compared modules are equal after LF normalization.\n"
    DIFF_REPORT_PATH.write_text(report_body, encoding="utf-8")

    summary_path = Path(__file__).with_suffix(".last_run.txt")
    summary_lines = [
        f"manifest={MANIFEST_PATH}",
        f"diff_report={DIFF_REPORT_PATH}",
        f"equal={manifest['equal_count']}",
        f"adapter_only={manifest['adapter_only_count']}",
        f"business_divergence={manifest['business_divergence_count']}",
        f"ok={ok}",
    ]
    for e in manifest["files"]:
        summary_lines.append(
            f"{e['path']}: kind={e.get('difference_kind')} equal={e.get('equal')} "
            f"app={e.get('app_sha256')} tbx={e.get('toolbox_sha256')} err={e.get('error')}"
        )
    summary_path.write_text("\n".join(summary_lines) + "\n", encoding="utf-8")


def main() -> int:
    if not APP_ROOT.is_dir():
        print(f"APP_ROOT not available: {APP_ROOT}", file=sys.stderr)
        return 2

    manifest = build_manifest(APP_ROOT, TOOLBOX_ROOT)
    ok = manifest.get("_ok", False)
    write_outputs(manifest)
    print(f"wrote {MANIFEST_PATH}")
    print(f"wrote {DIFF_REPORT_PATH}")
    print(
        f"equal={manifest['equal_count']} adapter_only={manifest['adapter_only_count']} "
        f"business_divergence={manifest['business_divergence_count']}"
    )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
